/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.antany.spark.learning;

import org.apache.hadoop.fs.FileSystem;
import org.apache.spark.sql.SparkSession;

import com.globalmentor.apache.hadoop.fs.BareLocalFileSystem;

public class Common {
    public static SparkSession getSparkSession() {
		SparkSession spark = SparkSession.builder().master("local[*]").appName("Learn").getOrCreate();
		spark.sparkContext().hadoopConfiguration().setClass("fs.file.impl", BareLocalFileSystem.class, FileSystem.class);
		
		return spark;
	}
}
